# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160806_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=350)),
                ('imagen', models.ImageField(null=True, upload_to='img_promo')),
                ('archivo', models.FileField(null=True, upload_to='img_promo')),
                ('alineamientox', models.CharField(choices=[('main-start', 'inicio'), ('main-center', 'centro'), ('main-start', 'fin')], max_length=15)),
                ('alineamientoy', models.CharField(choices=[('cross-start', 'inicio'), ('cross-center', 'centro'), ('cross-start', 'fin')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VistaPromocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.TextField(max_length=350),
        ),
    ]
