# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160806_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistapromocion',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='alineamientox',
            field=models.CharField(choices=[('main-start', 'inicio'), ('main-center', 'centro'), ('main-end', 'fin')], max_length=15),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='alineamientoy',
            field=models.CharField(choices=[('cross-start', 'inicio'), ('cross-center', 'centro'), ('cross-end', 'fin')], max_length=15),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='img_promo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_promo'),
        ),
    ]
