# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20160806_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
