# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20160806_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
